# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: "no"
    container_name: postgres
    hostname: postgres
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080